CREATE DATABASE TekstilProje;
GO
USE TekstilProje;
GO

--Kategori Tablolarý--
BEGIN;
CREATE TABLE Kategori (
	ID INT PRIMARY KEY IDENTITY(1,1),
	Kategori VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE MakineTuru (
	ID INT PRIMARY KEY IDENTITY(1,1),
	Tur VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE PersonelKonumu (
	ID INT PRIMARY KEY IDENTITY(1,1),
	Pozisyon VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Beden (
	ID INT PRIMARY KEY IDENTITY(1,1),
	Beden VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Renk (
	ID INT PRIMARY KEY IDENTITY(1,1),
	Renk VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IslemTuru (
	ID INT PRIMARY KEY IDENTITY(1,1),
	AdimAdi VARCHAR(100) NOT NULL UNIQUE,
	MakineTuruID INT FOREIGN KEY REFERENCES MakineTuru(ID),
	PersonelKonumuID INT FOREIGN KEY REFERENCES PersonelKonumu(ID)
);
END;
GO




--Veri Tablolarý--
BEGIN;
CREATE TABLE Urun (
	ID INT PRIMARY KEY IDENTITY(1,1),
	Adi VARCHAR(100) NOT NULL UNIQUE,
	Barkod VARCHAR(100) UNIQUE,
	KategoriID INT FOREIGN KEY REFERENCES Kategori(ID)
);

CREATE TABLE Makine (
	ID INT PRIMARY KEY IDENTITY(1,1),
	Model VARCHAR(100) NOT NULL,
	MakineTuruID INT FOREIGN KEY REFERENCES MakineTuru(ID)
);

CREATE TABLE Personel (
	ID INT PRIMARY KEY IDENTITY(1,1),
	Adi VARCHAR(100) NOT NULL,
	Soyadi VARCHAR(100) NOT NULL,
	Telefon VARCHAR(12) NOT NULL UNIQUE CHECK (Telefon LIKE '___ ___ ____'),
	PersonelKonumuID INT FOREIGN KEY REFERENCES PersonelKonumu(ID)
);

CREATE TABLE Kalip (
	ID INT PRIMARY KEY IDENTITY(1,1),
	Ad VARCHAR(100) NOT NULL,
	BedenID INT FOREIGN KEY REFERENCES Beden(ID)
);

CREATE TABLE UretimEmri (
	ID INT PRIMARY KEY IDENTITY(1,1),
	Tarih SMALLDATETIME NOT NULL,
	Adet INT NOT NULL CHECK(Adet > 0),
	UrunID INT FOREIGN KEY REFERENCES Urun(ID),
	BedenID INT FOREIGN KEY REFERENCES Beden(ID),
	RenkID INT FOREIGN KEY REFERENCES Renk(ID),
    VerenPersonelID INT FOREIGN KEY REFERENCES Personel(ID)
);

CREATE TABLE UretimAdimlari (
	ID INT PRIMARY KEY IDENTITY(1,1),
	AdimSirasi INT NOT NULL CHECK(AdimSirasi > 0),
	IslemTuruID INT FOREIGN KEY REFERENCES IslemTuru(ID),
	UrunID INT FOREIGN KEY REFERENCES Urun(ID)
);
END ;
GO

--Aracý Tablolar--
BEGIN;
CREATE TABLE Stok (
	UrunID INT FOREIGN KEY REFERENCES Urun(ID),
	BedenID INT FOREIGN KEY REFERENCES Beden(ID),
	RenkID INT FOREIGN KEY REFERENCES Renk(ID),
	Miktar INT NOT NULL CHECK(Miktar >= 0),
	PRIMARY KEY(UrunID ,BedenID, RenkID)
);

CREATE TABLE AdimIcinGerekenUrunler (
	UrunID INT FOREIGN KEY REFERENCES Urun(ID),
	UretimAdimlariID INT FOREIGN KEY REFERENCES UretimAdimlari(ID),
	Miktar INT NOT NULL CHECK(Miktar > 0)
	PRIMARY KEY(UrunID, UretimAdimlariID)
);

CREATE TABLE UretimKaydi (
	PersonelID INT FOREIGN KEY REFERENCES Personel(ID),
	UretimEmriID INT FOREIGN KEY REFERENCES UretimEmri(ID),
	UrunID INT FOREIGN KEY REFERENCES Urun(ID),
	UretimAdimlariID INT FOREIGN KEY REFERENCES UretimAdimlari(ID),
	MakineID INT FOREIGN KEY REFERENCES Makine(ID),
	KalipID INT FOREIGN KEY REFERENCES Kalip(ID),
	Miktar INT NOT NULL CHECK(Miktar > 0),
	Baslangic SMALLDATETIME NOT NULL,
	Bitis SMALLDATETIME NOT NULL
);
END;
GO
